version: "3.7"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/downloads:/downloads
      - ${APP_DATA_DIR}/data/sync:/sync
    ports:
      - ${APP_PORT}:8888
      - 55555:55555
    restart: unless-stopped