version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - tipi_main_network
      
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/movies:/movies #optional
      - ${ROOT_FOLDER}/app-data/transmission/data/downloads:/downloads #optional
    ports:
      - ${APP_RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - tipi_main_network