version: "3.7"

services:
  # unbound:
  #   image: "mvance/unbound:latest"
  #   container_name: unbound
  #   restart: unless-stopped
  #   hostname: "unbound"
  #   volumes:
  #     - "./unbound:/opt/unbound/etc/unbound/"
  #   networks:
  #     private_network:
  #       ipv4_address: 10.21.21.50
  wireguard:
    depends_on: [pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ} # Change to your timezone
      - SERVERPORT=51822
      - SERVERURL=mail.meienberger.dev #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=10.21.21.51 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0
    volumes:
      - ${APP_DATA_DIR}/data/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51822:51820/udp"
    dns:
      - 10.21.21.51
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
    networks:
      tipi_main_network:
        ipv4_address: 10.21.21.52

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      # - 10.21.21.50 # Points to unbound
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${APP_PASSWORD}
      PIHOLE_DNS_: 9.9.9.9 #127.0.0.1#5335
      FTLCONF_REPLY_ADDR4: 10.21.21.51
    cap_add:
      - NET_ADMIN
    networks:
      tipi_main_network:
        ipv4_address: 10.21.21.51
