http:
  routers:
    traefik:
      rule: "Host(`proxy.tipi.local`)"
      service: "api@internal"
      tls:
        domains:
          - main: "tipi.local"
            sans:
              - "*.tipi.local"
tls:
  certificates:
    - certFile: "/root/.config/ssl/local-cert.pem"
      keyFile: "/root/.config/ssl/local-key.pem"