http:
  routers:
    dashboard:
      rule: PathPrefix(`/`)
      service: dashboard
    
  services:
    dashboard:
      loadBalancer:
        servers:
        - port: 3000
    
# tls:
#   certificates:
#     - certFile: "/root/.config/ssl/local-cert.pem"
#       keyFile: "/root/.config/ssl/local-key.pem"