api:
  dashboard: true
  insecure: true


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /root/.config/dynamic.yml
    watch: true

entryPoints:
  webinsecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

log:
  level: DEBUG
