# api:
#   dashboard: true
#   insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  # TODO: Add TLS support
  # file:
  #   filename: /root/.config/dynamic.yml
  #   watch: true

entryPoints:
  web:
    address: ":80"
    # TODO: Redirect when TLS is working
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

log:
  level: DEBUG
