# Network
- name: Install avahi
  package:
    name: avahi
    state: latest
  when: ansible_os_family == "Arch"

- name: Install avahi
  package:
    name: avahi-daemon
    state: latest
  when: ansible_os_family == "Debian"

- name: Disable and stop sytemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Replace line in /etc/nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:.*'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'

- name: Allow port 5353 in UFW
  community.general.ufw:
    rule: allow
    port: 5353
    proto: udp

- name: Copy avahi template to /etc/avahi/services/tipi.service
  copy:
    src: "{{ playbook_dir }}/templates/avahi/tipi.service"
    dest: /etc/avahi/services/tipi.service
    group: avahi
    owner: avahi

- name: Start and enable avahi-daemon
  service:
    name: avahi-daemon
    state: restarted
    enabled: yes
###