- name: Install docker
  package:
    name:
      - docker
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: Add docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Check lsb_release -cs
  shell: lsb_release -cs
  register: lsb_release

- name: Add deb for bookworm release
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: lsb_release.stdout == "bookworm"

- name: Add deb for non-bookworm
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: lsb_release.stdout != "bookworm"

- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  when: ansible_os_family == "Debian"

- name: Check if docker-compose is installed
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_status

- name: Install docker-compose
  shell: 'curl -L "https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
  when: not docker_compose_status.stat.exists

- name: Make docker-compose executable
  shell: chmod +x /usr/local/bin/docker-compose

- name: Create group docker
  group:
    name: docker

- name: Put user in docker group
  user:
    name: "{{ username }}"
    group: docker

- name: Start docker service
  service:
    enabled: yes
    name: docker
    state: started
