- name: Install "pm2" package globally.
  community.general.npm:
    name: pm2
    global: yes

- name: Install "pnpm" package globally.
  community.general.npm:
    name: pnpm
    global: yes

- name: Run pm2 first time
  shell: pm2 list

- name: Enable pm2 as a service
  shell: sudo env PATH=$PATH:/usr/local/bin pm2 startup -u {{ username }}

- name: Install dependencies
  shell: cd {{ playbook_dir }} && pnpm install

- name: Clean packages
  shell: cd {{ playbook_dir }} && pnpm -r clean

- name: Remove packages/system-api/dist folder
  shell: rm -rf {{ playbook_dir }}/packages/system-api/dist

- name: Build packages
  become_user: "{{ username }}"
  shell: cd {{ playbook_dir }} && pnpm -r build-prod

- name: Check if app is already running
  become_user: "{{ username }}"
  shell: pm2 status system-api
  register: pm2_result

- name: Start app
  become_user: "{{ username }}"
  shell: cd {{ playbook_dir }}/../packages/system-api && pm2 start npm --name "system-api" -- start
  when: pm2_result.stdout.find("online") == -1

- name: Reload app
  become_user: "{{ username }}"
  shell: pm2 reload system-api
  when: pm2_result.stdout.find("online") != -1
