- name: Install "pm2" package globally.
  community.general.npm:
    name: pm2
    global: yes

- name: Run pm2 first time
  shell: pm2 list

- name: Enable pm2 as a service
  shell: sudo env PATH=$PATH:/usr/local/bin pm2 startup -u {{ username }}

- name: Install packages based on package.json.
  community.general.npm:
    path: "{{ playbook_dir }}/../system-api"

- name: Remove dist folder
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../system-api/dist"
    state: absent

- name: Build system-api
  shell: cd {{ playbook_dir }}/../system-api && npm run build

- name: Check if app is already running
  become_user: "{{ username }}"
  shell: pm2 status system-api
  register: pm2_result

- name: Start app
  become_user: "{{ username }}"
  shell: cd {{ playbook_dir }}/../system-api && pm2 start npm --name "system-api" -- start
  when: pm2_result.stdout.find("online") == -1

- name: Reload app
  become_user: "{{ username }}"
  shell: pm2 reload system-api
  when: pm2_result.stdout.find("online") != -1
