# Base config
- name: Install zsh package
  package:
    name:
      - zsh
      - git
    state: latest

- name: Check if .zshrc exists
  stat:
    path: "/home/{{ username }}/.zshrc"
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: "/home/{{ username }}/.oh-my-zsh"
  register: stat_ohmyzsh_result

# Oh-my-zsh installation
- name: Get oh-my-zsh install script
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install.sh
    mode: "0555"
  when: not stat_ohmyzsh_result.stat.exists

- name: Run installation script
  become_user: "{{ username }}"
  shell:
    cmd: yes | /tmp/install.sh
    creates: /home/{{ username }}/.oh-my-zsh"
  when: not stat_ohmyzsh_result.stat.exists

- name: Creating new /home/{{ username }}/.zshrc
  copy:
    src: /home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/{{ username }}/.zshrc
    remote_src: yes
  when: not stat_rc_result.stat.exists

# Powerlevel10k configuration
- name: Clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Enable powerlevel10k
  lineinfile:
    dest: /home/{{ username }}/.zshrc
    regexp: "^ZSH_THEME="
    line: "ZSH_THEME={{ zsh_theme }}"

- name: Check if .p10k.zsh exists
  stat:
    path: "/home/{{ username }}/.p10k.zsh"
  register: stat_p10k_result

- name: Copy template to .p10k.zsh
  copy:
    src: "{{ playbook_dir }}/templates/zsh/p10k-template.zsh"
    dest: /home/{{ username }}/.p10k.zsh
  when: not stat_p10k_result.stat.exists

- name: Store .zshrc in variable
  shell: "cat /home/{{ username }}/.zshrc"
  register: zshrc_result

- name: Add line to .zshrc
  shell: 'echo "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh" >> /home/{{ username }}/.zshrc'
  when: zshrc_result.stdout.find('source ~/.p10k.zsh') == -1

# Final teardown
- name: Change default shell to zsh
  become: yes
  user:
    name: "{{ username }}"
    shell: /bin/zsh
