services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    ports:
      - ${APP_PORT}:80
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_FOLDER}:/srv
      - ${APP_DATA_DIR}/data/filebrowser.db:/database/filebrowser.db
      - ${APP_DATA_DIR}/data/settings.json:/config/settings.json
    networks:
      - tipi_main_network
