services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    ports:
      - ${APP_PORT}:80
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/../..:/srv
      - ${APP_DATA_DIR}/data/db:/database
      - ${APP_DATA_DIR}/data/config:/config
    networks:
      - tipi_main_network
