version: "3.7"

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${APP_PASSWORD}
      PIHOLE_DNS_: 127.0.0.1#5335
      FTLCONF_REPLY_ADDR4: 192.168.2.132
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "true"
      DNSMASQ_LISTENING: single
    networks:
      - tipi_main_network