version: '3.7'
services:
  wg-easy:
      network_mode: "container:gluetun"
      image: 'weejewel/wg-easy:latest'
      restart: unless-stopped
      volumes:
        - ${APP_DATA_DIR}:/etc/wireguard
      environment:
        WG_HOST: 'wireguard.meienberger.dev'
        PASSWORD: 'password'
        WG_DEFAULT_DNS: 'pihole'
        # WG_POST_UP: ...
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv4.ip_forward=1
      # ports:
      #   - '51820:51820/udp'
      #   - '51821:51821/tcp'
      labels:
        traefik.enable: true
        traefik.http.routers.traefik.rule: Host(`wg.${DOMAIN}`)
        traefik.http.services.traefik.loadbalancer.server.port: $APP_WGEASY_PORT
