version: '3.7'
services:
  wg-easy:
      image: 'weejewel/wg-easy'
      restart: unless-stopped
      volumes:
        - ${APP_DATA_DIR}:/etc/wireguard
      environment:
        WG_HOST: 'wireguard.meienberger.dev'
        PASSWORD: 'moneyprintergobrrr'
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv4.ip_forward=1
      ports:
        - '51820:51820/udp'
        - '51821:51821/tcp'
      networks:
        default:
            ipv4_address: $APP_WG_EASY_IP