version: "3.7"

services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:1.19.2
    restart: unless-stopped
    ports:
      - "${APP_FRESHRSS_PORT}:80"
    volumes:
      - ${APP_DATA_DIR}/data/:/var/www/FreshRSS/data
      - ${APP_DATA_DIR}/extensions/:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'
      TZ: $TZ
    networks:
      - tipi_main_network
    labels:
        traefik.enable: true
        traefik.http.routers.freshrss.rule: Host(`freshrss.tipi.local`)
        traefik.http.routers.freshrss.service: freshrss
        traefik.http.routers.freshrss.tls: true
        traefik.http.routers.freshrss.entrypoints: websecure
        traefik.http.services.freshrss.loadbalancer.server.port: 80