name: Docker build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get tag from VERSION file
        id: meta
        run: |
          VERSION=$(cat VERSION)
          TAG=${VERSION}
          echo "::set-output name=tag::${TAG}"
      -
        name: Build and push dashboard
        uses: docker/build-push-action@v2
        with:
          context: ./packages/dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: meienberger/tipi-dashboard:latest,meienberger/tipi-dashboard:${{ steps.meta.outputs.TAG }}
          cache-from: type=registry,ref=meienberger/tipi-dashboard:latest
          cache-to: type=inline
      -
        name: Build and push api
        uses: docker/build-push-action@v2
        with:
          context: ./packages/system-api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: meienberger/tipi-api:latest,meienberger/tipi-api:${{ steps.meta.outputs.TAG }}
          cache-from: type=registry,ref=meienberger/tipi-api:latest
          cache-to: type=inline