name: Tipi CI
on:
  push:

env:
  ROOT_FOLDER: /test
  JWT_SECRET: "secret"
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm -r lint
      
      - name: Run tests
        run: pnpm -r test

  test-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create user and group
        run: useradd -u 1000 test

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      # This is normally done in the start script but
      # we need to do it here to cache the dependency
      - name: Install ansible
        run: pip install -r requirements.txt

      - name: Run install script
        run: sudo ./scripts/start.sh

