
name: Build & Deploy
on:
  push:
    branches:    
      - 'release/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          draft: false
          prerelease: false