name: Verify release

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            VERSION

      - name: Ensure env.MATCHED_FILES has VERSION in it
        id: check-version
        run: |
          if [[ -z "${{ env.MATCHED_FILES }}" ]]; then
            echo "::error::VERSION not modified"
            exit 1
          fi
          if [[ ! "${{ env.MATCHED_FILES }}" =~ VERSION ]]; then
            echo "::error::VERSION not modified"
            exit 1
          fi

          
